// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $AddToCart from "./islands/AddToCart.tsx";
import * as $AddToCartButton_CartSaverButton from "./islands/AddToCartButton/CartSaverButton.tsx";
import * as $AddToCartButton_magento from "./islands/AddToCartButton/magento.tsx";
import * as $FiltersIsland from "./islands/FiltersIsland.tsx";
import * as $Header_Bartop from "./islands/Header/Bartop.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart from "./islands/Header/Cart.tsx";
import * as $Header_CartSide from "./islands/Header/CartSide.tsx";
import * as $Header_CartSideV2 from "./islands/Header/CartSideV2.tsx";
import * as $Header_NavbarMenuItems from "./islands/Header/NavbarMenuItems.tsx";
import * as $Header_Produtos from "./islands/Header/Produtos.tsx";
import * as $Header_ProdutosModal from "./islands/Header/ProdutosModal.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $ImageGallerySlider from "./islands/ImageGallerySlider.tsx";
import * as $Institucional_Accordion from "./islands/Institucional/Accordion.tsx";
import * as $ModalProvider from "./islands/ModalProvider.tsx";
import * as $ModalSample from "./islands/ModalSample.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $PDPAlert from "./islands/PDPAlert.tsx";
import * as $ProductShareModal from "./islands/ProductShareModal.tsx";
import * as $QuantitySelector from "./islands/QuantitySelector.tsx";
import * as $ReviewsTab from "./islands/ReviewsTab.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShowMore from "./islands/ShowMore.tsx";
import * as $SliderCarousel from "./islands/SliderCarousel.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $SliderJSV2 from "./islands/SliderJSV2.tsx";
import * as $Toast from "./islands/Toast.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import * as $simulateShipping from "./islands/simulateShipping.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
  },
  islands: {
    "./islands/AddToCart.tsx": $AddToCart,
    "./islands/AddToCartButton/CartSaverButton.tsx":
      $AddToCartButton_CartSaverButton,
    "./islands/AddToCartButton/magento.tsx": $AddToCartButton_magento,
    "./islands/FiltersIsland.tsx": $FiltersIsland,
    "./islands/Header/Bartop.tsx": $Header_Bartop,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart.tsx": $Header_Cart,
    "./islands/Header/CartSide.tsx": $Header_CartSide,
    "./islands/Header/CartSideV2.tsx": $Header_CartSideV2,
    "./islands/Header/NavbarMenuItems.tsx": $Header_NavbarMenuItems,
    "./islands/Header/Produtos.tsx": $Header_Produtos,
    "./islands/Header/ProdutosModal.tsx": $Header_ProdutosModal,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/ImageGallerySlider.tsx": $ImageGallerySlider,
    "./islands/Institucional/Accordion.tsx": $Institucional_Accordion,
    "./islands/ModalProvider.tsx": $ModalProvider,
    "./islands/ModalSample.tsx": $ModalSample,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/PDPAlert.tsx": $PDPAlert,
    "./islands/ProductShareModal.tsx": $ProductShareModal,
    "./islands/QuantitySelector.tsx": $QuantitySelector,
    "./islands/ReviewsTab.tsx": $ReviewsTab,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShowMore.tsx": $ShowMore,
    "./islands/SliderCarousel.tsx": $SliderCarousel,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/SliderJSV2.tsx": $SliderJSV2,
    "./islands/Toast.tsx": $Toast,
    "./islands/WishlistButton.tsx": $WishlistButton,
    "./islands/simulateShipping.tsx": $simulateShipping,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
