// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/addGiftItem.ts";
import * as $$$$$$$$$1 from "./actions/addGiftWrapping.ts";
import * as $$$$$$$$$2 from "./actions/addSellerCode.ts";
import * as $$$$$$$$$3 from "./actions/cartSaver.ts";
import * as $$$$$$$$$4 from "./actions/removeGiftItem.ts";
import * as $$$$$$$$$5 from "./actions/removeGiftWrapping.ts";
import * as $$$$$$$$$6 from "./actions/removeSellerCode.ts";
import * as $$$$$$$$$7 from "./actions/simularFrete.ts";
import * as $$$$$$$$$8 from "./actions/updateLowStockProducts.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/algolia.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/workflows.ts";
import * as $$$$$$$$$$$4 from "./apps/magento.ts";
import * as $$$$$$$$$$$5 from "./apps/site.ts";
import * as $$$2 from "./loaders/abTestScript.ts";
import * as $$$3 from "./loaders/algolia/listIndex.ts";
import * as $$$4 from "./loaders/algolia/products/list.ts";
import * as $$$6 from "./loaders/algolia/products/listingPage.ts";
import * as $$$5 from "./loaders/algolia/products/listRecomended.ts";
import * as $$$7 from "./loaders/algolia/products/suggestions.ts";
import * as $$$8 from "./loaders/algolia/recommends/client.ts";
import * as $$$9 from "./loaders/availableIcons.ts";
import * as $$$10 from "./loaders/cookies/expireCookies.ts";
import * as $$$11 from "./loaders/cookies/shouldReloadCart.ts";
import * as $$$12 from "./loaders/decoRecordProducts.ts";
import * as $$$13 from "./loaders/features/features.ts";
import * as $$$14 from "./loaders/getCartFromRecords.ts";
import * as $$$15 from "./loaders/giftItem/gift.ts";
import * as $$$16 from "./loaders/giftWrapping/cart.ts";
import * as $$$17 from "./loaders/giftWrapping/get.ts";
import * as $$$18 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$19 from "./loaders/productsFromRecords.ts";
import * as $$$20 from "./loaders/removeWishlist.ts";
import * as $$$21 from "./loaders/sellerCode/getCode.ts";
import * as $$$22 from "./loaders/skuList.ts";
import * as $$$23 from "./loaders/suggetionsFromRecords.ts";
import * as $$$$$$0 from "./sections/About/About.tsx";
import * as $$$$$$1 from "./sections/Animation/Animation.tsx";
import * as $$$$$$3 from "./sections/BenefitsRule/BenefitsRule.tsx";
import * as $$$$$$2 from "./sections/BFShowcaseBanner/BFShowcaseBanner.tsx";
import * as $$$$$$4 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$5 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$6 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$7 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$9 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$10 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$11 from "./sections/Container.tsx";
import * as $$$$$$12 from "./sections/Content/Benefits.tsx";
import * as $$$$$$13 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$14 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$15 from "./sections/Content/Faq.tsx";
import * as $$$$$$16 from "./sections/Content/Features.tsx";
import * as $$$$$$17 from "./sections/Content/Hero.tsx";
import * as $$$$$$18 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$19 from "./sections/Content/Intro.tsx";
import * as $$$$$$20 from "./sections/Content/Logos.tsx";
import * as $$$$$$21 from "./sections/Content/Partners.tsx";
import * as $$$$$$22 from "./sections/Content/RichText.tsx";
import * as $$$$$$23 from "./sections/Content/Table.tsx";
import * as $$$$$$24 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$25 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$26 from "./sections/Footer/Footer.tsx";
import * as $$$$$$27 from "./sections/Gallery.tsx";
import * as $$$$$$28 from "./sections/Header/Header.tsx";
import * as $$$$$$29 from "./sections/Header/HeaderV2.tsx";
import * as $$$$$$30 from "./sections/HitLoadings/HitLoadings.tsx";
import * as $$$$$$31 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$32 from "./sections/Images/Carousel.tsx";
import * as $$$$$$33 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$34 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$35 from "./sections/Images/SmallBanner.tsx";
import * as $$$$$$36 from "./sections/Institucional/CodeOfEthicsAndConduct.tsx";
import * as $$$$$$37 from "./sections/Institucional/ExchangePolicy.tsx";
import * as $$$$$$38 from "./sections/Institucional/GiftCard.tsx";
import * as $$$$$$40 from "./sections/Institucional/partnershipsAndEvents.tsx";
import * as $$$$$$41 from "./sections/Institucional/pickupInStoreAndExpressDelivery.tsx";
import * as $$$$$$39 from "./sections/Institucional/PromotionRules.tsx";
import * as $$$$$$42 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$43 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$44 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$45 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$46 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$47 from "./sections/Pageview.tsx";
import * as $$$$$$48 from "./sections/Personalizacao.tsx";
import * as $$$$$$49 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$50 from "./sections/Product/NotFound.tsx";
import * as $$$$$$51 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$52 from "./sections/Product/ProductCardUnique.tsx";
import * as $$$$$$53 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$54 from "./sections/Product/ProductGalleryInfo.tsx";
import * as $$$$$$55 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$56 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$57 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$58 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$59 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$60 from "./sections/RedirectPagesExecptions.tsx";
import * as $$$$$$61 from "./sections/SEO/SeoPDPV2Custom.tsx";
import * as $$$$$$62 from "./sections/SEO/SeoPLPV2Custom.tsx";
import * as $$$$$$63 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$64 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$65 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/abTestScript.ts": $$$2,
    "site/loaders/algolia/listIndex.ts": $$$3,
    "site/loaders/algolia/products/list.ts": $$$4,
    "site/loaders/algolia/products/listingPage.ts": $$$6,
    "site/loaders/algolia/products/listRecomended.ts": $$$5,
    "site/loaders/algolia/products/suggestions.ts": $$$7,
    "site/loaders/algolia/recommends/client.ts": $$$8,
    "site/loaders/availableIcons.ts": $$$9,
    "site/loaders/cookies/expireCookies.ts": $$$10,
    "site/loaders/cookies/shouldReloadCart.ts": $$$11,
    "site/loaders/decoRecordProducts.ts": $$$12,
    "site/loaders/features/features.ts": $$$13,
    "site/loaders/getCartFromRecords.ts": $$$14,
    "site/loaders/giftItem/gift.ts": $$$15,
    "site/loaders/giftWrapping/cart.ts": $$$16,
    "site/loaders/giftWrapping/get.ts": $$$17,
    "site/loaders/icons.ts": $$$18,
    "site/loaders/Layouts/ProductCard.tsx": $$$0,
    "site/loaders/List/Sections.tsx": $$$1,
    "site/loaders/productsFromRecords.ts": $$$19,
    "site/loaders/removeWishlist.ts": $$$20,
    "site/loaders/sellerCode/getCode.ts": $$$21,
    "site/loaders/skuList.ts": $$$22,
    "site/loaders/suggetionsFromRecords.ts": $$$23,
  },
  "sections": {
    "site/sections/About/About.tsx": $$$$$$0,
    "site/sections/Animation/Animation.tsx": $$$$$$1,
    "site/sections/BenefitsRule/BenefitsRule.tsx": $$$$$$3,
    "site/sections/BFShowcaseBanner/BFShowcaseBanner.tsx": $$$$$$2,
    "site/sections/Cards/IconCardsCarousel.tsx": $$$$$$4,
    "site/sections/Cards/IconCardsCarouselWithImage.tsx": $$$$$$5,
    "site/sections/Cards/ImageCardsCarousel.tsx": $$$$$$6,
    "site/sections/Cards/ImageCardsCarouselWithImage.tsx": $$$$$$7,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$8,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$9,
    "site/sections/Category/CategoryList.tsx": $$$$$$10,
    "site/sections/Container.tsx": $$$$$$11,
    "site/sections/Content/Benefits.tsx": $$$$$$12,
    "site/sections/Content/BlogPosts.tsx": $$$$$$13,
    "site/sections/Content/CallToAction.tsx": $$$$$$14,
    "site/sections/Content/Faq.tsx": $$$$$$15,
    "site/sections/Content/Features.tsx": $$$$$$16,
    "site/sections/Content/Hero.tsx": $$$$$$17,
    "site/sections/Content/ImageSection.tsx": $$$$$$18,
    "site/sections/Content/Intro.tsx": $$$$$$19,
    "site/sections/Content/Logos.tsx": $$$$$$20,
    "site/sections/Content/Partners.tsx": $$$$$$21,
    "site/sections/Content/RichText.tsx": $$$$$$22,
    "site/sections/Content/Table.tsx": $$$$$$23,
    "site/sections/Content/Testimonials.tsx": $$$$$$24,
    "site/sections/Content/TextWithImage.tsx": $$$$$$25,
    "site/sections/Footer/Footer.tsx": $$$$$$26,
    "site/sections/Gallery.tsx": $$$$$$27,
    "site/sections/Header/Header.tsx": $$$$$$28,
    "site/sections/Header/HeaderV2.tsx": $$$$$$29,
    "site/sections/HitLoadings/HitLoadings.tsx": $$$$$$30,
    "site/sections/Images/BannerGrid.tsx": $$$$$$31,
    "site/sections/Images/Carousel.tsx": $$$$$$32,
    "site/sections/Images/ImageGallery.tsx": $$$$$$33,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$34,
    "site/sections/Images/SmallBanner.tsx": $$$$$$35,
    "site/sections/Institucional/CodeOfEthicsAndConduct.tsx": $$$$$$36,
    "site/sections/Institucional/ExchangePolicy.tsx": $$$$$$37,
    "site/sections/Institucional/GiftCard.tsx": $$$$$$38,
    "site/sections/Institucional/partnershipsAndEvents.tsx": $$$$$$40,
    "site/sections/Institucional/pickupInStoreAndExpressDelivery.tsx": $$$$$$41,
    "site/sections/Institucional/PromotionRules.tsx": $$$$$$39,
    "site/sections/Links/LinkTree.tsx": $$$$$$42,
    "site/sections/Links/Shortcuts.tsx": $$$$$$43,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$44,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$45,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$46,
    "site/sections/Pageview.tsx": $$$$$$47,
    "site/sections/Personalizacao.tsx": $$$$$$48,
    "site/sections/Product/ImageGalleryFrontBack.tsx": $$$$$$49,
    "site/sections/Product/NotFound.tsx": $$$$$$50,
    "site/sections/Product/NotFoundChallenge.tsx": $$$$$$51,
    "site/sections/Product/ProductCardUnique.tsx": $$$$$$52,
    "site/sections/Product/ProductDetails.tsx": $$$$$$53,
    "site/sections/Product/ProductGalleryInfo.tsx": $$$$$$54,
    "site/sections/Product/ProductShelf.tsx": $$$$$$55,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$56,
    "site/sections/Product/SearchResult.tsx": $$$$$$57,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$58,
    "site/sections/Product/Wishlist.tsx": $$$$$$59,
    "site/sections/RedirectPagesExecptions.tsx": $$$$$$60,
    "site/sections/SEO/SeoPDPV2Custom.tsx": $$$$$$61,
    "site/sections/SEO/SeoPLPV2Custom.tsx": $$$$$$62,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$63,
    "site/sections/Social/WhatsApp.tsx": $$$$$$64,
    "site/sections/Theme/Theme.tsx": $$$$$$65,
  },
  "actions": {
    "site/actions/addGiftItem.ts": $$$$$$$$$0,
    "site/actions/addGiftWrapping.ts": $$$$$$$$$1,
    "site/actions/addSellerCode.ts": $$$$$$$$$2,
    "site/actions/cartSaver.ts": $$$$$$$$$3,
    "site/actions/removeGiftItem.ts": $$$$$$$$$4,
    "site/actions/removeGiftWrapping.ts": $$$$$$$$$5,
    "site/actions/removeSellerCode.ts": $$$$$$$$$6,
    "site/actions/simularFrete.ts": $$$$$$$$$7,
    "site/actions/updateLowStockProducts.ts": $$$$$$$$$8,
  },
  "apps": {
    "site/apps/deco/algolia.ts": $$$$$$$$$$$0,
    "site/apps/deco/analytics.ts": $$$$$$$$$$$1,
    "site/apps/deco/records.ts": $$$$$$$$$$$2,
    "site/apps/deco/workflows.ts": $$$$$$$$$$$3,
    "site/apps/magento.ts": $$$$$$$$$$$4,
    "site/apps/site.ts": $$$$$$$$$$$5,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
